#!/bin/bash
PREFIX= #`pwd | awk -F /usr/bin '{print($1)}'`
if [ -f ${PREFIX}/etc/default/smcms ]; then
	. ${PREFIX}/etc/default/smcms
fi

DB_USER_NAME=${SAMCMS_DB_USER}`test ! -z ${SAMCMS_DB_USER}||echo "smcms"`
echo "db user = ${DB_USER_NAME}, pwd=${PWD}"
DB_HOST=${SAMCMS_DB_ADDRESS}`test ! -z ${SAMCMS_DB_ADDRESS}||echo "127.0.0.1"`
DB_DB_NAME=${SAMCMS_DB_NAME}`test ! -z ${SAMCMS_DB_NAME}||echo "samcms"`

CMD="psql -h ${DB_HOST} -U ${DB_USER_NAME} -d ${DB_DB_NAME} -f"

if ! [ -d ./log ];
then
	mkdir ./log
else
	if [ -e ./log/install_log ]; then
		rm ./log/install_log
	fi
	touch ./log/install_log
	test -d ./log/archive || mkdir ./log/archive
	mv ./log/install_* ./log/archive
fi

inbase() {
	if ! [ -d $1 ]; then
		echo "error: $1 not dir!"
		exit 1;
	fi
	
	NUM_FILES=`ls -1 $1 | grep ".sql" | wc -l`;
	I=1;
	echo "Add from $1:"
	while [ $(( $I - 1 )) -ne $NUM_FILES ]
	do
		TMP_STR=`ls -1 $1 | head -$I | tail -1`
		$CMD $1/$TMP_STR >> ./log/install_log 2>&1
		ERROR_CHCK=`cat ./log/install_log | grep ERROR | wc -l;`
		echo -e "\t $I) $TMP_STR"
		if [ $ERROR_CHCK -ne 0 ];  then
			echo "error: SQL not correct!"
			cat ./log/install_log | sed -e '/./{H;$!d;}' -e 'x;/ERROR/!d;'
			mv ./log/install_log ./log/install_ERR_`date +%Y%m%d_%T`
			exit 1;
		fi
		echo -e "\n" >> ./log/install_log
		I=$(( $I + 1 ))
	done
}

help() {
	echo -e "  -h \t for help"
	echo -e "  -i \t install [modules name from ./modules] "
	echo -e "     \t default base modules install from ./modules/base"
	echo -ne "    available modules: "
	ls ./modules
	echo -e "  -v \t release info and about smcms"
}

if [ -z $1 ]; then
	help;
	exit 1;
fi

psql -h ${DB_HOST} -U ${DB_USER_NAME} -d postgres -c "DROP DATABASE ${DB_DB_NAME}"
psql -h $DB_HOST -U $DB_USER_NAME -d postgres -c "CREATE DATABASE ${DB_DB_NAME}"

inbase ${PREFIX}/usr/share/smcms/modules/tables
inbase ${PREFIX}/usr/share/smcms/modules/base
inbase ${PREFIX}/usr/share/smcms/modules/doc
#inbase ./modules/tables
#inbase ./modules

mv ./log/install_log ./log/install_`date +%Y%m%d_%T`

exit 0;

