#!/bin/sh

### BEGIN INIT INFO
# Provides:			samcms
# Required-Start:	$local_fs $remote_fs $network $syslog
# Required-Stop:	$local_fs $remote_fs $network $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	starts the samcms system
# Description:		starts samcms using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/samcms
NAME=samcms
DESC=samcms
SAMCMS_PID=/var/run/samcms.pid

# Include samcms defaults if available
if [ -f /etc/default/samcms ]; then
	. /etc/default/samcms
	DAEMON_OPTS="-a ${SAMCMS_ADDR} -p ${SAMCMS_PORT} -u ${SAMCMS_USER} -g ${SAMCMS_GROUP} -F 4 -P ${SAMCMS_PID} -- ${SAMCMS_SCRIPT} ${SAMCMS_SCRIPT_OPTIONS}"
fi

test -x $SAMCMS_SCRIPT || exit 0
test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
	start)
		echo -n "Starting $DESC: "
		start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
			--exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		killall ${SAMCMS_SCRIPT}
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON || true
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --quiet --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON || true
		sleep 1
		start-stop-daemon --start --quiet --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" samcms && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0

